---
- name: Configure Nginx and Certbot
  hosts: webservers
  become: yes
  vars:
    app_port: "{{ app_port | default(3000) }}"
  tasks:
    - name: Create Nginx configuration file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ subdomain }}.{{ domain }}
      notify:
        - Reload Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/{{ subdomain }}.{{ domain }}
        dest: /etc/nginx/sites-enabled/{{ subdomain }}.{{ domain }}
        state: link
      notify:
        - Reload Nginx

    - name: Obtain SSL certificate with Certbot
      command: certbot --nginx -d {{ subdomain }}.{{ domain }}
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded